spring.application.name=backend-spring
server.port=${PORT:3001}
server.error.whitelabel.enabled=false
spring.jpa.hibernate.ddl-auto=none
management.endpoints.web.base-path=/actuator
spring.datasource.url=jdbc:postgresql://localhost:5432/plans
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.locations=classpath:db/migration
